### ISSUE TITLE
openMP support?

### ISSUE THREAD

**Issue by nbanik** [jobovy/streamgap-pepper#7]
Hi, 
    I ran the following command (with the paths modified for the local machine) 
python simulate_streampepper.py --outdens=/data/bovy/streamgap-pepper/gd1_onetime/gd1_t1.0_6.5_dens.dat --outomega=/data/bovy/streamgap-pepper/gd1_onetime/gd1_t1.0_6.5_omega.dat -t 1. -M 6.5 -n 1002 -X 5. 

on my linux laptop and on my university cluster on 4 cores. On my laptop it ran and the outputs were generated in around 10 mins, whereas on the cluster it's been running for over 1.5 hrs with no outputs. I do get the galpy warnings https://github.com/jobovy/galpy/issues/317 , but I do see that it says "galpyWarning: Using C implementation to integrate orbits". 

So I am not sure whether the issues with galpy are causing the code to run slow. 

I will be running the above code with multiple impacts with say -t 256samplings or more, so I am keen on setting the code up on a cluster. 

Thanks,
Nil

**Comment by jobovy** [comment]
The streamgap-pepper code is not parallelized and I have no immediate intention of adding this support (my own approach has been to simply run many instances of the code in parallel to obtain different simulations in parallel, not to use parallel processing to generate a single simulation).

If the code hasn't generated any output in the ``outdens`` and ``outomega`` files, then there's probably something wrong, because it should at least quickly write the first line in those files. You could try to debug this by putting in print statements throughout the code to figure out where it hangs, it's hard to know what's going on without more information.

It could be that there is an additional problem with the C code, related to jobovy/galpy#317 that is maybe more subtle. So perhaps fixing that (by switching compilers?) will work.

Just to avoid frustration going forward, I want to make it clear that this ``streamgap-pepper`` code is mainly provided as an explanation of what we did in this paper and I have only very limited time to support this code (it is *not* provided as a maintained, supported piece of code; this is the motivation for keeping it separate from ``galpy`` itself, which is maintained and supported). I hope you can understand this (the alternative is to not share the code, which is what most other people do).

**Comment by nbanik** [comment]
Thanks, I understand.

**Comment by jobovy** [comment]
Did fixing the compile issue actually fix this?

**Comment by nbanik** [comment]
Yes, I changed compilers and now I no longer get the orbitintegration warnings. I ran a code on the cluster and it was done within 12 mins (similar to my laptop).

**Comment by jobovy** [comment]
Okay, so you couldn't get it to work with ``icc``?

It's good that the code works, but you *are* supposed to get the ``galpyWarning: Using C implementation to integrate orbits`` when C is being used. But if the code runs and produces reasonable output, then it's probably okay.

**Comment by nbanik** [comment]
No, I wasn't able to get it working with intel compilers. 

>It's good that the code works, but you are supposed to get the galpyWarning: Using C implementation to integrate orbits when C is being used 

Yes, I do get that warning. What I meant was "integrateFullOrbit_c extension module not loaded" warnings, those don't appear anymore.

**Comment by jobovy** [comment]
Ah okay, I didn't realize you were getting the ``integrateFullOrbit_c extension module not loaded`` warning (that explains why the code was slow).
